services:
  - type: web
    name: portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application --workers 4 --threads 4 --worker-tmp-dir /dev/shm"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.11.4
    plan: free

databases:
  - name: portfolio_db
    databaseName: portfolio
    user: portfolio_user
    plan: free
