databases:
  - name: portfolio_db
    databaseName: portfolio
    user: portfolio_user
    plan: free

services:
  - type: web
    name: portfolio
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn portfolio.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.0
    plan: free
