# Generated by Django 5.2 on 2025-04-29 09:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('DA', 'Data Analysis'), ('ML', 'Machine Learning'), ('DV', 'Data Visualization'), ('ST', 'Statistical Analysis'), ('DP', 'Data Processing')], max_length=2)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('github_link', models.URLField(blank=True)),
                ('live_demo_link', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('date_collected', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=50)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='datascience.project')),
            ],
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('PLT', 'Plot'), ('CHT', 'Chart'), ('GRF', 'Graph'), ('MAP', 'Map'), ('DBD', 'Dashboard')], max_length=3)),
                ('image', models.ImageField(upload_to='visualizations/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('code_snippet', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='datascience.project')),
            ],
        ),
    ]
