# Generated by Django 5.2 on 2025-05-02 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datascience', '0002_remove_dataset_format_remove_dataset_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='github_link',
            field=models.URLField(blank=True, help_text='GitHub repository URL'),
        ),
    ]
